services:
    # NGINX: Server
    nginx:
        container_name: ${APP_NAME}-nginx
        image: nginx:latest
        restart: always
        volumes:
            - ./:/var/www/html/
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        extra_hosts:
            - "host.docker.internal:host-gateway"


    # NGINX: PHP
    php-fpm:
        container_name: ${APP_NAME}-php-fpm
        build: ./.docker/php-fpm
        volumes:
            - ./:/var/www/html/
        ports:
            - 9000:9000

    # Apache: Server (with PHP)
#    apache-php:
#        container_name: ${APP_NAME}-apache-php
#        build: ./.docker/apache-php
#        restart: always
#        volumes:
#            - ./:/var/www/html:delegated
#        ports:
#            - 80:80
#        environment:
#            APACHE_RUN_USER: "#1000"
#        extra_hosts:
#            - "host.docker.internal:host-gateway"

    # MariaDB: Server
    mariadb:
        image: mariadb:latest
        container_name: ${APP_NAME}-mariadb
        restart: always
        environment:
            MARIADB_USER: ${DATABASE_MARIADB_USER}
            MARIADB_PASSWORD: ${DATABASE_MARIADB_PASSWORD}
            MARIADB_ROOT_PASSWORD: ${DATABASE_MARIADB_PASSWORD}
            MARIADB_DATABASE: ${DATABASE_MARIADB_NAME}
        volumes:
            - "./.docker/.data/mariadb/data:/var/lib/mysql/data/"
            - "./.docker/.data/mariadb/logs:/var/lib/mysql/logs/"
        ports:
            - 3306:3306

    # MySQL: Server
#    mysql:
#        container_name: ${APP_NAME}-mysql
#        image: mysql:5.7
#        volumes:
#            - ./.docker/.data/mysql:/var/lib/mysql:delegated
#            - ./.docker/mysql:/docker-entrypoint-initdb.d
#        environment:
#            MYSQL_DATABASE: ${DATABASE_MYSQL_NAME}
#            MYSQL_USER: ${DATABASE_MYSQL_USER}
#            MYSQL_PASSWORD: ${DATABASE_MYSQL_PASSWORD}
#            MYSQL_ROOT_PASSWORD: ${DATABASE_MYSQL_PASSWORD}
#        ports:
#            - 3306:3306
#        command: mysqld --sql_mode="" --lower_case_table_names=1

    # MySQL/MariaDB: PhpMyAdmin
    pma:
        container_name: ${APP_NAME}-pma
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOSTS: "mariadb"
        ports:
            - 8080:80

    # Redis: Server
    redis:
        container_name: ${APP_NAME}-redis
        image: redis:latest
        command: --loglevel verbose
        ports:
            - 6380:6380

    # Redis: PhpRedisAdmin
    phpredisadmin:
        container_name: ${APP_NAME}-pra
        image: erikdubbelboer/phpredisadmin
        environment:
            - ADMIN_USER=root
            - ADMIN_PASS=root
            - REDIS_1_HOST=redis
            - REDIS_1_PORT=6380
        depends_on:
            - redis
        links:
            - redis
        ports:
            - 8081:80
